### ISSUE TITLE
Collection data disappearing after sync

### ISSUE THREAD

**Issue by bob-albright** [Nathansbud/BoredGamer#5]
3 out of 4 times when you go to sync plays and/or your collection, the collection information is being wiped out.  It appears to be a timing issue of when the BGG api is being called.  A different user found that if you manually trigger this url first (https://boardgamegeek.com/xmlapi2/collection?username=bob_albright&own=1), then when you try to sync the collection, it will work.

**Comment by Nathansbud** [comment]
Howdy! I didn't realize anybody else was using this—this was mostly for my own personal use, haha. I haven't noticed any adverse affects when syncing (though perhaps I just have a small collection); can you clarify what you mean by "collection information is being wiped out"? Sorry if this lead to any data loss on your end!

**Comment by bob-albright** [comment]
> Howdy! I didn't realize anybody else was using this—this was mostly for my own personal use, haha. I haven't noticed any adverse affects when syncing (though perhaps I just have a small collection); can you clarify what you mean by "collection information is being wiped out"? Sorry if this lead to any data loss on your end!

After a data update, your collection will show 0 games, even if it previously showed games.  and FYI, BoredGamerTools.com is used by a ton of BGG users... :)

**Comment by bob-albright** [comment]
If you want you can check my data.  I currently am showing 249 games in my collection.  http://www.boredgamertools.com/collection.php?username=bob_albright
once you confirm that, I can do a data update so you can track what happens.

**Comment by Nathansbud** [comment]
Ah, that explains it—BoredGamerTools isn't this repo! This is for a tiny little command line tool that looks like this:

<img width="543" alt="image" src="https://user-images.githubusercontent.com/20943979/159072480-04ad52a4-c2b3-4cbb-a2cf-f486c5b450fd.png">

Hopefully they have a good portal to report the issue, I couldn't find a GitHub repo for their project :(

**Comment by bob-albright** [comment]
ah ha..!  my bad, sorry
